Add support for bfe.u64 and bfi.b64
NVIDIA/cub pull request #117
Opened 2017-09-21 17:08 UTC by aterenin

The cub::BFE and cub::BFI wrappers are useful, because nvcc likes to place bitfield structs in local memory rather than registers, making it far more efficient to work with 64-bit integers instead. 

At present, CUB only provides wrappers for 32-bit bit field manipulation: 64-bit BFE is handled via the bit shift operator rather than inline assembly, and 64-bit BFI is not supported at all.

This PR adds support for 64-bit BFI and BFI. It changes the return type of cub::BFE to match that of the PTX intrinsic, and adds templates for BFI that match BFE.

2020-10-21 21:04 UTC, allisonvacanti commented
Looks like this was closed accidentally during the repo move. Reopening.

2020-11-19 19:19 UTC, allisonvacanti commented
It looks like 64-bit BFE/BFI were added since this PR was added, but the current implementation doesn't use inline ptx for the 64-bit versions. We should check what the optimizer outputs for the current version and switch to inline ptx if needed.

2021-01-01 03:49 UTC, brycelelbach requested changes

2021-01-01 03:49 UTC, brycelelbach commented on cub/util_ptx.cuh
> +#if CUB_PTX_ARCH >= 200
We don't support anything before SM35 anymore, so no need for the `#ifdef`.

2021-01-01 03:49 UTC, brycelelbach commented on cub/util_ptx.cuh
>  #if CUB_PTX_ARCH >= 200
We don't support anything before SM35 anymore, so no need for the `#ifdef`.

2021-01-01 03:49 UTC, brycelelbach commented on cub/util_ptx.cuh
> +#if CUB_PTX_ARCH >= 200
We don't support anything before SM35 anymore, so no need for the `#ifdef`.

2021-01-01 03:49 UTC, brycelelbach commented on cub/util_ptx.cuh
> +        "=l"((unsigned long long int) ret) : "l"((unsigned long long int) y), "l"((unsigned long long int) x), "r"(bit_start), "r"(num_bits));
Please use `std::uint64_t`, etc, instead of variable-width types like `unsigned long long int`.

2021-01-01 03:49 UTC, brycelelbach commented on cub/util_ptx.cuh
> +    unsigned long long int MASK_Y = ~MASK_X;
Please use `std::uint64_t`, etc, instead of variable-width types like `unsigned long long int`.

2023-02-20 16:27 UTC, jrhemstad commented
@aterenin we'd still welcome this functionality, but it has grown quite out of date. I'm going to close this PR for now, but feel free to reopen if you decide you would like to update it and move forward.

2023-02-20 16:27 UTC, closed without merging

2023-02-20 16:37 UTC, aterenin commented
Thanks for the response! I would've loved to do this, but it has been so long that I no longer have an idea what is going on. Anyone who needs this is welcome to build on my PR.