Add CUB_NVCXX_QA_COMPAT mode in CMake.
NVIDIA/cub pull request #251
Opened 2020-12-15 21:58 UTC by allisonvacanti

This mode:
a) Emits configuration error if more than one dialect option is enabled, and
b) Removes the dialect information from target / executable names.

Fixes NVIDIA/cub#250.

2020-12-18 19:24 UTC, brycelelbach commented on CMakeLists.txt
> +option(CUB_NVCXX_QA_COMPAT "Use shorter names and force a single dialect." OFF)
I'd prefer a name that describes what it does, not what it is. I'd suggest something like `CUB_ENABLE_CPP_DIALECT_IN_EXE_NAMES` (defaulted to `ON`). I don't think the name needs to capture the fact that you get a configuration error if you try to use it with multiple C++ dialects; that just seems like a natural consequence.

2020-12-18 19:25 UTC, brycelelbach requested changes
Looks good, but I'm not thrilled with the name. I'd prefer something that describes what it does, not what it's used for.

2021-01-29 14:09 UTC, allisonvacanti commented
@brycelelbach Updated with requested changes.

run tests

2021-02-08 20:18 UTC, brycelelbach approved these changes
Approved, please just fix the comment I pointed out. Let me know when this is merged so I can add CUB tests to NVC++'s internal testing!

2021-02-09 20:28 UTC, merged