Fix block shuffle
NVIDIA/cub pull request #311
Opened 2021-05-26 10:11 UTC by senior-zero

In order to fix [the issue](https://github.com/NVIDIA/cub/issues/264) with `BlockShuffle::Down` function I've written tests for `BlockShuffle` . It turned out that it was broken because of the wrong `_TempStorage` type which also led to extra shared memory usage.

2021-05-26 10:21 UTC, senior-zero commented
This PR also fixes [this issue](https://github.com/NVIDIA/cub/issues/268).

2021-05-26 22:14 UTC, allisonvacanti requested changes

2021-05-26 22:14 UTC, allisonvacanti commented on test/test_block_shuffle.cu
> +    SingleItemTestHelper<data_type, items_per_thread, threads_in_block, OffsetUpTest>().run(num_items,
Can you add a comment explaining what this helper is used for? It looks like this becomes a no-op when `items_per_thread` != 1, but this is only invoked (in main) with `items_per_thread` == 1.

We should probably add some test cases where `items_per_thread` > 1.

2021-06-01 19:39 UTC, allisonvacanti commented
DVS CL: 30027318
gpuCI: NVIDIA/thrust#1451

2021-06-08 16:28 UTC, allisonvacanti approved these changes

2021-06-08 16:29 UTC, merged