[WIP] 64-bit Offsets in Onesweep Sorting
NVIDIA/cub pull request #340
Opened 2021-07-03 22:18 UTC by canonizer

- 64-bit `OffsetT` is supported for onesweep sorting
- for decoupled look-back, the partition kernel is broken into smaller parts (as before), and a separate 32-bit type is used there
- for histograms, 32-bit counters are used in shared memory and `OffsetT`-sized counters in global memory

2022-01-12 20:03 UTC, allisonvacanti requested changes
Some minor changes suggested inline, but otherwise I'm happy with this 👍

It'd be good to rebase this on `main` to make sure that we didn't miss any other deprecated APIs from #364.

Once this is rebased and the comments addressed I'll start testing.

2022-01-14 02:18 UTC, canonizer commented on cub/agent/agent_radix_sort_histogram.cuh
> +        const OffsetT MAX_PORTION_SIZE = 1 << 30;
Done, using "portion" consistently for this concept.

2022-01-14 02:19 UTC, canonizer commented on cub/block/radix_rank_sort_operations.cuh
> +// T == int, unsigned int, unsigned long long
I found a simpler solution: just use `OffsetT == unsigned long long` for the 64-bit case. This allows using `atomicAdd()` functions, and there's no need to define `AtomicAdd()`.

2022-01-14 02:19 UTC, canonizer commented on cub/agent/agent_radix_sort_histogram.cuh
> +    typedef uint32_t ShmemCounterT;
Done.

2022-01-14 02:19 UTC, canonizer commented on cub/device/device_radix_sort.cuh
> +                  !Equals<typename std::remove_cv<NumItemsT>::type, bool>::VALUE,
Done.

2022-01-14 02:19 UTC, canonizer commented on cub/device/device_radix_sort.cuh
> +    using Type = typename If<sizeof(NumItemsT) <= 4, uint32_t, uint64_t>::Type;
Done.

2022-01-14 02:20 UTC, canonizer commented on test/test_device_radix_sort.cu
> +
Done.

2022-01-14 17:31 UTC, allisonvacanti approved these changes

2022-01-19 20:07 UTC, allisonvacanti commented
Rebased to pull in recent fixes in `main`.

2022-01-19 20:10 UTC, allisonvacanti commented
gpuCI: NVIDIA/thrust#1593
DVS CL: 30893016

2022-01-20 19:07 UTC, allisonvacanti commented
There were a few issues in CI: NVIDIA/thrust#1593

From the clang-9 build, I didn't check the others:

Missing `util_math.cuh` header maybe?
```
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/clang++-9 -DCUB_IGNORE_DEPRECATED_CPP_11 -DCUB_WRAPPED_NAMESPACE=wrapped_cub -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_WRAPPED_NAMESPACE=wrapped_thrust -I/workspace/dependencies/cub -I/workspace -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -O3 -DNDEBUG -Xcompiler=-Werror -Xcompiler=-Wall -Xcompiler=-Wextra -Xcompiler=-Winit-self -Xcompiler=-Woverloaded-virtual -Xcompiler=-Wcast-qual -Xcompiler=-Wpointer-arith -Xcompiler=-Wunused-local-typedef -Xcompiler=-Wvla -Xcompiler=-Wgnu -Xcompiler=-Wno-gnu-zero-variadic-macro-arguments -Xcompiler=-Wno-unused-function -Xcompiler=-Wno-deprecated-declarations -Xcudafe=--display_error_number -Xcudafe=--promote_warnings -Wno-deprecated-gpu-targets -std=c++11 -MD -MT dependencies/cub/CMakeFiles/cub.cpp11.headers.dir/headers/agent/agent_radix_sort_histogram.cuh.cu.o -MF dependencies/cub/CMakeFiles/cub.cpp11.headers.dir/headers/agent/agent_radix_sort_histogram.cuh.cu.o.d -x cu -c /workspace/build/dependencies/cub/headers/agent/agent_radix_sort_histogram.cuh.cu -o dependencies/cub/CMakeFiles/cub.cpp11.headers.dir/headers/agent/agent_radix_sort_histogram.cuh.cu.o
/workspace/dependencies/cub/cub/agent/agent_radix_sort_histogram.cuh(229): error: namespace "wrapped_cub::cub" has no member "DivideAndRoundUp"
```

Using `'` as a digit separator isn't supported in C++11:
```
[6109/6477] Building CUDA object dependencies/cub/test/CMakeFiles/cub.cpp11.test.device_radix_sort.bytes_4.pairs_3.dir/test_device_radix_sort.cu.o
FAILED: dependencies/cub/test/CMakeFiles/cub.cpp11.test.device_radix_sort.bytes_4.pairs_3.dir/test_device_radix_sort.cu.o 
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/clang++-9 -DCUB_IGNORE_DEPRECATED_CPP_11 -DTEST_KEY_BYTES=4 -DTEST_VALUE_TYPE=3 -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -I/workspace/dependencies/cub/test -I/workspace/dependencies/cub -I/workspace -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -O3 -DNDEBUG -Xcompiler=-Werror -Xcompiler=-Wall -Xcompiler=-Wextra -Xcompiler=-Winit-self -Xcompiler=-Woverloaded-virtual -Xcompiler=-Wcast-qual -Xcompiler=-Wpointer-arith -Xcompiler=-Wunused-local-typedef -Xcompiler=-Wvla -Xcompiler=-Wgnu -Xcompiler=-Wno-gnu-zero-variadic-macro-arguments -Xcompiler=-Wno-unused-function -Xcompiler=-Wno-deprecated-declarations -Xcudafe=--display_error_number -Xcudafe=--promote_warnings -Wno-deprecated-gpu-targets -std=c++11 -MD -MT dependencies/cub/test/CMakeFiles/cub.cpp11.test.device_radix_sort.bytes_4.pairs_3.dir/test_device_radix_sort.cu.o -MF dependencies/cub/test/CMakeFiles/cub.cpp11.test.device_radix_sort.bytes_4.pairs_3.dir/test_device_radix_sort.cu.o.d -x cu -c /workspace/dependencies/cub/test/test_device_radix_sort.cu -o dependencies/cub/test/CMakeFiles/cub.cpp11.test.device_radix_sort.bytes_4.pairs_3.dir/test_device_radix_sort.cu.o
/workspace/dependencies/cub/test/test_device_radix_sort.cu:1366:66: error: missing terminating ' character [-Werror,-Winvalid-pp-token]
        const std::size_t large_num_items = std::size_t(4'350'000'007ull);
```

2022-01-24 22:57 UTC, canonizer commented
Fixed both and rebased.

2022-01-24 23:30 UTC, allisonvacanti commented
Did one more rebase to bring in some CI fixes -- gpuCI should not have any failures if all goes well.

gpuCI: NVIDIA/thrust#1593
DVS CL: 30911286

2022-01-25 18:54 UTC, allisonvacanti commented
main *should* be clear now. Trying again.

gpuCI: NVIDIA/thrust#1593
DVS CL: 30914954

2022-01-27 21:36 UTC, allisonvacanti commented
All set, thanks again @canonizer!

2022-01-27 21:38 UTC, merged