Update header tests to check for termios.h's B0 macro.
NVIDIA/cub pull request #392
Opened 2021-10-25 20:19 UTC by allisonvacanti

Will need to be rebased / tested after NVIDIA/thrust#1548 is merged.

2022-02-07 19:36 UTC, allisonvacanti commented
gpuCI: NVIDIA/thrust#1551

2022-02-08 09:19 UTC, senior-zero requested changes

2022-02-08 09:19 UTC, senior-zero commented on cmake/header_test.in
> +#define B0 THRUST_MACRO_CHECK("B0", termios.h)
Should it be `CUB_MACRO_CHECK` instead?

2022-02-08 15:38 UTC, allisonvacanti commented on cmake/header_test.in
> +#define B0 THRUST_MACRO_CHECK("B0", termios.h)
Yup! Fixed.

2022-02-08 17:31 UTC, merged