[WIP] Port unique by key from thrust
NVIDIA/cub pull request #405
Opened 2021-11-12 23:40 UTC by zasdfgbnm

2021-11-13 01:41 UTC, zasdfgbnm commented
@allisonvacanti This should be ready. The tests are passing locally on my computer. The only thing missing are docs.

2021-11-13 18:39 UTC, zasdfgbnm commented
doc is done

2021-11-13 18:39 UTC, zasdfgbnm commented
cc @ptrblck @ngimel

2022-01-12 21:06 UTC, allisonvacanti requested changes
Apologies for taking so long to get to this -- I've pointed out some issues inline. Most of them are related to recent changes to cub, mainly #364 and  #403. Otherwise this LGTM 👍

 I'll start testing once:
- [ ] Review comments are addressed.
- [ ] Branch is rebased.
- [ ] Branch is squashed to remove temporary WIP commits.

2022-01-12 21:06 UTC, allisonvacanti commented on test/test_device_select_unique_by_key.cu
> +#ifdef CUB_TEST_MINIMAL
These are no longer used as of #403. See [these changes](https://github.com/NVIDIA/cub/pull/403/files#diff-95a45d0e7312e0f0952a14a791cafac27ef85578189fa38492d1a6d2adabcdf7) to `test_device_select_unique.cu` that are aimed at reducing build/run times. This should be updated to use the same patterns.

2022-01-14 19:23 UTC, zasdfgbnm commented
All done

2022-01-19 20:27 UTC, allisonvacanti commented
Rebased to bring in recent CI fixes.

2022-01-19 20:30 UTC, allisonvacanti commented
gpuCI: NVIDIA/thrust#1596
DVS CL: 30893135

2022-01-20 01:30 UTC, zasdfgbnm commented
Just fixed an error on C++11 detected by the CI

2022-01-20 19:40 UTC, allisonvacanti commented
Restarted CI on new version:

gpuCI: NVIDIA/thrust#1596
DVS CL: 30897739

2022-01-21 06:43 UTC, zasdfgbnm commented
I fixed the IsPointer deprecation error in CI. It's strange that my local doesn't detect it.

2022-01-21 17:04 UTC, allisonvacanti commented
> I fixed the IsPointer deprecation error in CI.

Thanks, I'll restart the builds in a moment.

> It's strange that my local doesn't detect it.

The default value for the CMake option `THRUST_IGNORE_DEPRECATED_API` changed about a month ago -- we used to ignore deprecation warnings while building tests, but now we're able to leave them on. Your CMake build has probably caching the old default value.

Running `cmake -DTHRUST_IGNORE_DEPRECATED_API=OFF .` from your build directory should update this setting and enable the warnings.

2022-01-21 17:08 UTC, allisonvacanti commented
gpuCI: NVIDIA/thrust#1596
DVS CL: 30902006

2022-01-24 19:16 UTC, allisonvacanti approved these changes
Tests are passing 👍

2022-01-24 19:17 UTC, merged