Allow cub headers to be installed into a subdirectory of `include`
NVIDIA/cub pull request #415
Opened 2021-12-17 17:31 UTC by robertmaynard

Needed to fix https://github.com/NVIDIA/thrust/issues/1541

2022-01-10 17:43 UTC, allisonvacanti requested changes
Aside from some minor style points mentioned inline, this looks good to me.

2022-01-10 17:43 UTC, allisonvacanti commented on cmake/CubInstallRules.cmake
> +  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
Add quotes around the path.

2022-01-10 17:43 UTC, allisonvacanti commented on cub/cmake/cub-header-search.cmake
> +set_property(CACHE _CUB_VERSION_INCLUDE_DIR PROPERTY TYPE INTERNAL)
Missing newline at EOF

2022-01-10 17:43 UTC, allisonvacanti commented on cmake/CubInstallRules.cmake
> +configure_file("${CUB_SOURCE_DIR}/cub/cmake/cub-header-search.cmake.in"
Add a comment explaining why this is needed (similar to the Thrust PR)

2022-01-10 17:43 UTC, allisonvacanti commented on cub/cmake/cub-config-version.cmake
> +include(${CMAKE_CURRENT_LIST_DIR}/cub-header-search.cmake)
Add quotes around path

2022-01-10 17:43 UTC, allisonvacanti commented on cub/cmake/cub-header-search.cmake
> +    ${CMAKE_CURRENT_LIST_DIR}/../..            # Source tree
Quotes

2022-01-10 17:43 UTC, allisonvacanti commented on cub/cmake/cub-header-search.cmake.in
> +    ${CMAKE_CURRENT_LIST_DIR}/../../../@CMAKE_INSTALL_INCLUDEDIR@ # Install tree
Quotes

2022-01-10 19:30 UTC, robertmaynard commented
> Aside from some minor style points mentioned inline, this looks good to me.

All style issues are now resolved.

2022-01-12 18:55 UTC, allisonvacanti approved these changes

2022-01-12 18:55 UTC, merged