Eliminate device synchronization in CDP version of segmented sort
NVIDIA/cub pull request #445
Opened 2022-03-18 13:06 UTC by senior-zero

This PR eliminates the device-side usage of the `cudaDeviceSynchronize` function which was depricated in the CUDA Toolkit 11.6. Since in the #409 @fkallen reported usage of the segmented soft in the CDP mode, it whould be great if @fkallen could verify the changes.

2022-03-21 21:41 UTC, allisonvacanti requested changes
LGTM, some minor updates needed.

2022-03-21 21:41 UTC, allisonvacanti commented on cub/device/dispatch/dispatch_segmented_sort.cuh
> -      if (debug_synchronous)
Let's leave the device-side `debug_synchronous` syncs in for now (also add them in the continuation handler if needed).

2022-03-21 21:41 UTC, allisonvacanti commented on cub/device/dispatch/dispatch_segmented_sort.cuh
> +    if (CUB_IS_HOST_CODE)
Leave this in for device code, the `SyncStream` implementation will be updated and will still provide useful logging.

2022-03-21 21:41 UTC, allisonvacanti commented on cub/device/dispatch/dispatch_segmented_sort.cuh
> +      #if CUB_INCLUDE_HOST_CODE
Leave this in for device code (see other comments)

2022-03-22 07:07 UTC, fkallen commented
The (simple) test code from #409 is working.

2022-03-22 17:39 UTC, allisonvacanti commented
gpuCI: NVIDIA/thrust#1641

2022-03-22 17:46 UTC, allisonvacanti commented
Will need to restart tests later, looks like the github outage is affecting things at the moment.

2022-03-24 17:46 UTC, allisonvacanti approved these changes

2022-03-24 17:47 UTC, merged