Better error message for no GPU or incompatible GPU
NVIDIA/cub pull request #577
Opened 2022-09-21 17:56 UTC by zkhatami

To give user some clue what's happening if the program gets compiled on a node with no GPU or if it gets compiled with different compute capability than the one it's running on. In both scenarios no good error message were produced before. The proposed changes will improve the user experience and make it easier for users to troubleshoot problems.

This fix is for addressing the issue#1785 reported on Thrust https://github.com/NVIDIA/thrust/issues/1785

2022-09-21 18:39 UTC, zkhatami commented
From issue#1785 on thrust (https://github.com/NVIDIA/thrust/issues/1785), for this small test case:

`#include <thrust/device_vector.h>
#include <thrust/sort.h>
int main() {
  thrust::device_vector<int> dv;
  thrust::sort(dv.begin(), dv.end());
}`

when compiled with -gpu=cc60 and then run it on a system with cc80, the error message would be:
`
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 1st step: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.
Aborted
`

This doesn't help user to understand what's happening. I tried to address it in this change so that better message will show up:
`
Incompatible GPU: you are trying to run this program on sm_80, different from the one that it was compiled for
`

2022-09-21 21:55 UTC, jrhemstad commented on cub/util_device.cuh
> +      }
Was this for debugging? I don't think we want to keep this.

2022-09-21 21:57 UTC, jrhemstad commented on cub/util_device.cuh
> +                            sm_version/100, (sm_version%100)/10);
`printf` isn't a very robust or canonical way of reporting errors. This should really be an exception, but CUB doesn't currently throw exceptions.

2022-09-21 21:59 UTC, jrhemstad reviewed
The other problem with this approach is it is dependent on our current strategy of using `cudaFuncGetAttributes` for querying the PTX version at runtime.

This will no longer work when we migrate to the alternative approach described here: https://github.com/NVIDIA/cub/issues/556

2022-09-22 16:20 UTC, zkhatami commented
Is there any release targeted for #556? If its unknown, then might be beneficial from user perspective to have this fix with current CUB design. 
In this proposal, is there anyway to test for the GPU incompatibility in the very beginning, like the one that we currently have with using the failure on cudaFuncGetAttributes?

2022-09-22 17:17 UTC, jrhemstad commented
> have this fix with current CUB design.

I agree, however, I'm not sure about our ability to preserve this functionality into the future. 

> In this proposal, is there anyway to test for the GPU incompatibility in the very beginning, like the one that we currently have with using the failure on cudaFuncGetAttributes?

That's the problem, I don't think we do.

2022-10-10 10:51 UTC, senior-zero requested changes
Thank you for the contribution! Some minor questions below

2022-10-10 10:51 UTC, senior-zero commented on cub/util_device.cuh
> +                    printf("Incompatible GPU: you are trying to run this program on sm_%d%d, "
Should we include something like stdio in this header if we are going to use printf unconditionally?

2022-10-10 10:51 UTC, senior-zero commented on cub/util_device.cuh
> +                    printf("Incompatible GPU: you are trying to run this program on sm_%d%d, "
Also, should it be `fprintf(stderr, ...)` instead?

2022-10-10 10:51 UTC, senior-zero commented on cub/util_device.cuh
> +                            "different from the one that it was compiled for\n",
Optional: we could report actual architectures we were compiled against. We are using the list in any case for our namespace generation:
```cpp
#define CUB_DETAIL_MAGIC_NS_BEGIN inline namespace CUB_DETAIL_MAGIC_NS_NAME(CUB_VERSION, NV_TARGET_SM_INTEGER_LIST) {
#else // not defined(_NVHPC_CUDA)
#define CUB_DETAIL_MAGIC_NS_BEGIN inline namespace CUB_DETAIL_MAGIC_NS_NAME(CUB_VERSION, __CUDA_ARCH_LIST__) {
```
We could probably concatenate appropriate lists and stringify the result as a follow up at some point.

2022-10-10 10:51 UTC, senior-zero commented on cub/util_device.cuh
> +        }
Some style guides: 
```suggestion
        if (result != cudaSuccess) 
        {
          int sm_version{};
          int device{-1};

          if (CubDebug(cudaGetDevice(&device)) == cudaSuccess) 
          {
            if (CubDebug(SmVersionUncached(sm_version, device)) == cudaSuccess) 
            {
              printf("Incompatible GPU: you are trying to run this program on sm_%d%d, "
                     "different from the one that it was compiled for\n",
                     sm_version / 100, (sm_version % 100) / 10);
            }
          }
        }
```

2022-10-10 17:22 UTC, dkolsen-pgi commented
I agree with Jake that writing error messages to stdout or stderr is not the best way to report this problem.  The use cases that we care about are calling Thrust.  NVC++ stdpar never calls CUB directly.  Thrust usually reports device-side problems by throwing a `thrust::system_error` exception.  A lack of GPU or a GPU with an incompatible architecture should also be reported with a `thrust::system_error` exception, with a a custom message in the exception that clearly explains the problem.

I wonder if `get_ptx_version` in `thrust/system/cuda/detail/core/util.h` would be a better place to put this logic.

2023-01-13 21:47 UTC, zkhatami commented
@jrhemstad @dkolsen-pgi @senior-zero 
I've moved my changes to thrust instead based on David's suggestion. Here is my pull request:
https://github.com/NVIDIA/thrust/pull/1848

Still, I'm not able to add any reviewers here. The Reviewers button is still disabled for me.
Would you please take a look at the changes and share your comments with me? Thanks!

2023-01-26 06:36 UTC, senior-zero commented
Hello @zkhatami!

> I've moved my changes to thrust instead based on David's suggestion. 

If the change is now on the thrust part, can this PR be closed? 

> Still, I'm not able to add any reviewers here. 
The thrust PR seems to have 3 reviewers at the moment. Let me know if I can help requesting reviews from other maintainers.

2023-01-27 22:32 UTC, zkhatami commented
I'm closing this pull since I've moved the changes to thrust.

2023-01-27 22:32 UTC, closed without merging